#!/usr/bin/env python3

class Solution:
    def maxNumOfMarkedIndices(self, nums: List[int]) -> int:
        
        nums.sort()
        ct = 0
        p1, p2 = 0, len(nums) //2 
        for p1 in range(len(nums)//2):
            while p2 < len(nums):
                if nums[p2] >= 2*nums[p1]:
                    ct += 2
                    p2 += 1
                    break
                else:
                    p2 += 1
        return ct    
               
