#!/usr/bin/env python3

class Solution:
    def maxScore(self, nums: List[int]) -> int:
        
        tot = 0
        pre = []
        nums.sort(reverse=True) #desc list to max pos vals when summed
        
        for num in nums:
            tot += num
            pre.append(tot) #lists all sums
            
        ct = 0
        for i in pre:
            if i > 0:
                ct += 1
        return ct
