#!/usr/bin/env python3

class Solution:
    def circularGameLosers(self, n: int, k: int) -> List[int]:

        # 1 indexed n friends
        seen = [1] #game ends when val repeated. return range n not in list
        current = 1
        mult = 1

        while True:
            current += k * mult 
            mult += 1
            if current > n: 
                current = current % n
            if current == 0:
                current = n
            if current not in seen: seen.append(current)
            else: break

        seen.sort()
        ans = []
        for i in range(1, n+1):
            if i not in seen: ans.append(i)

        return ans
            


