#!/usr/bin/env python3

class Solution:
    def coloredCells(self, n: int) -> int:
        
        x = 2*n -1
        ct = x
        while x > 1:
            x-=2
            ct += 2*x
        return ct
        
