#!/usr/bin/env python3

class Solution:
    def passThePillow(self, n: int, time: int) -> int:
        
       
        #lap = 2*(n-1)
        t = time % (2*(n-1))
        
                          
        #to R end in n-1          
        if t <= n-1:
            return t +1   ## 1 indexed
        
        elif t >= n:
            t -= (n-1)  ## now at R end
            return n-t
